version: '3.8'

services:

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - "9123:9000"
    volumes:
      - ./app:/var/www/web
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8989:80"
    volumes:
      - ./app:/var/www/web
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database
      - php

